-- GENERATED ALWAYS AS IDENTITY rejects any INSERT/upsert that specifies a
-- value for the column at all, even the row's own existing value — and the
-- client's sync always upserts full rows (spread ...row), so the moment an
-- item had been pulled down once with a short_id, editing it again and
-- syncing sent that short_id right back and every such upsert started
-- failing ("cannot insert a non-DEFAULT value into column short_id").
-- BY DEFAULT still auto-assigns on a real insert with no value given, but
-- tolerates an explicit value (e.g. the row's own current one) instead of
-- rejecting the whole statement.
alter table items alter column short_id set generated by default;
